# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: 
url: https://lxiange.com
# image_url: /images
image_url: https://statics.lxiange.com
# image_url: https://lxiange-1251082959.file.myqcloud.com

date_format: "ordinal"
title: Lxiange's Blog
author: Xiang Li 

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /feed.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
error_mode: strict
markdown: kramdown
kramdown:
    input: GFM
paginate: 9
permalink: /posts/:title.html
gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "lxiange"
      category: "uncategorized"
  -
    scope:
      path: ""
      type: "wiki"
    values:
      layout: "wiki"
      author: "lxiange"



# ---------------- #
#      Comments    #
# ---------------- #
duoshuo_short_name: lxiange
disqus_short_name: lxiange
enable_duoshuo: false
enable_disqus: true

# ---------------- #
#       Server     #
# ---------------- #
port: 4000
host: 0.0.0.0


