# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: 
url: http://lxiange.github.io
date_format: "ordinal"
title: lxiange's Blog
author: Xiang Li 

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /feed.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
paginate: 9
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
duoshuo_short_name: lxiange
changyan: false
