version: '3'
services:
  jekyll:
    image: jekyll/jekyll
    ports:
    - 4000:4000
    volumes:
    - .:/srv/jekyll
    entrypoint: /bin/sh -c
    command: ["bundle install && jekyll serve --watch"]
