version: '3'
services:
  jekyll:
    image: jekyll/jekyll
    ports:
    - 4000:4000
    volumes:
    - .:/srv/jekyll
    entrypoint: /bin/sh -c
    command: ["bundle install && jekyll serve --watch"]
    environment: 
    - HTTP_PROXY=http://30.17.236.48:1080
    - HTTPS_PROXY=https://30.17.236.48:1080
    restart: always

